POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "firstName" : "Russell",
    "lastName" : "Peiris",
    "email" : "ardpeiris@gmail.com",
    "password" : "admin123",
    "picturePath" : "example",
    "location" : "Negombo",
    "occupation" : "Undergraduate"
}
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email" : "ardpeiris@gmail.com",
    "password" : "admin123"
}